replicaCount: 1

image:
  repository: 071750954579.dkr.ecr.ap-southeast-2.amazonaws.com/nginx-sre
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

nameOverride: ""
fullnameOverride: ""



