replicaCount: 1 # replicaCount 由 HPA 控制，啟用 autoscaling 時此值僅作為初始值

image:
  repository: placeholder  # 由 CI/CD 動態覆蓋
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

nameOverride: ""
fullnameOverride: ""