apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-sre.fullname" . }}
  labels:
    app: {{ include "nginx-sre.fullname" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "nginx-sre.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "nginx-sre.fullname" . }}
    spec:
      containers:
        - name: nginx-sre
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}